name: Update Mindmaps

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          persist-credentials: true

      - name: Generate files
        run: |
          # Aquí va tu script real de generación
          echo "<html><body>Mapa generado</body></html>" > index.html
          echo "# Dev Mindmaps" > README.md

      - name: Commit and push changes
        uses: EndBug/add-and-commit@v9
        with:
          message: "Update index.html and README.md automatically"
          add: "index.html README.md"